name: "Auto merge dependabot bumps"

on:
  workflow_run:
    types:
      - completed
    workflows:
      - "Continuous Integration"

steps:
  - name: Merge me!
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ridedott/merge-me-action@v2
    with:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PRESET: DEPENDABOT_MINOR
