name: CI Pipeline
on: [push, pull_request]
jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest]
        php-versions: ['7.3', '7.4', '8.0']
        experimental: [false]
        include:
          - php: "8.0"
            experimental: true
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl
          ini-values: post_max_size=256M, short_open_tag=On
          tools: phpunit
        env:
          update: true

      - name: Update composer to v2
        run: composer self-update --2

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader --ignore-platform-req=php

      - name: Test with phpunit
        run: vendor/bin/phpunit

      - name: Check codestyle
        run: vendor/bin/phpcs -s

      - name: Check code with Psalm
        run: vendor/bin/psalm --shepherd
